spring:
  application:
    name: petAdopt
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.195.225:3306/pet_adopt?serverTimezone=GMT%2B8
    username: root
    password: 5wRMmkN3
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  tencent:
    domain:
    region: ap-XXX
    bucketName: XXX
    secretId: XXXXXX
    secretKey: XXXXXX
    styleRule:
    thumbnailStyleRule: "!Photo_Compression"
    fileTypes: ## 允许上传的文件类型
      - png
      - jpg
      - jpeg
      - gif
      - bmp
      - svg